# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c93c8a92b22324d10962d1d8a74c320af5251d12a248909c717665e02f8570ffeaf489f9666af2f2b574bc245bceaea92f0a5a77a069e954e0a5fe41fec0a9d5

test:
  secret_key_base: e928c31076765568ad1dc4338b17489c052d4abcdcadb40a8426ae769908a93d8500531210a78e8ffe8c3231fc4ce83babf06b6c4d80472e1aba5cd4ced6e9d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
